### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by farid-temuri** [translation-gang/docs-ru#343]
Список файлов, которые еще надо перевести:

- [X] https://github.com/translation-gang/docs-ru/issues/286
- [x] https://github.com/translation-gang/docs-ru/issues/287
- [x] https://github.com/translation-gang/docs-ru/issues/278
- [ ] https://github.com/translation-gang/docs-ru/issues/294
- [ ] https://github.com/translation-gang/docs-ru/issues/318
- [x] https://github.com/translation-gang/docs-ru/issues/319
- [x] https://github.com/translation-gang/docs-ru/issues/320
- [ ] https://github.com/translation-gang/docs-ru/issues/352
- [ ] https://github.com/translation-gang/docs-ru/issues/353
- [ ] https://github.com/translation-gang/docs-ru/issues/354
- [x] https://github.com/translation-gang/docs-ru/issues/356
- [X] https://github.com/translation-gang/docs-ru/pull/345
- [ ] https://github.com/translation-gang/docs-ru/pull/346
- [X] https://github.com/translation-gang/docs-ru/pull/347

Пока проверил все, кроме [интерактивного учебника](https://github.com/translation-gang/docs-ru/tree/main/src/tutorial/src). Позже сяду и закончу. Можно прям отсюда брать, что делать.

**Comment by farid-temuri** [comment]
На данный момент все проверил, когда сделаем все выше - можно релизить имхо. 
Мелкие правки потом будут делаться по мере поступления. А как деплой будет - я не знаю, было бы круто - если бы кто-то подсказал.

**Comment by farid-temuri** [comment]
@Ibochkarev. Заранее извиняюсь за наивные вопросы, если такими кажутся, но я не нашел на них ответов.
1) Почему перевод не с остальными в [официально организации vue](https://github.com/vuejs-translations/)
2) Как будет релиз проходить?
3) Может стоит уже релизнуть? Так как пока люди вообще узнают, что перевод вышел на русском и заходить на сайт - доделается перевод глоссария (единственная не переведенная страница)

**Comment by bogdankorshunov** [comment]
@farid-temuri [вот тут](https://github.com/vuejs-translations/docs-uk) прям на баннере написано, почему vue русский не завозят

**Comment by farid-temuri** [comment]
@bogdankorshunov Я не нашел упоминания Русского языка на этой странице. Русский язык - это не Путин и СВО. Я - Таджик вообще и мне нету дела до этого, как и многим Русским. Если нету более объективных причин - можно написать уже чтобы добавили на сайт русский перевод.

**Comment by srsad** [comment]
@bogdankorshunov первый абзац [Code Of Conduct](https://vuejs.org/about/coc.html#code-of-conduct)

**Comment by Leronez** [comment]
По моему опыту перевода документации vue-router и pinia могу сказать, никаких проблем нет. 
Ссылки переводов на русский язык этих библиотек включены в официальную документацию. 
https://pinia-ru.netlify.app/
https://vue-router-ru.netlify.app/

**Comment by bogdankorshunov** [comment]
@srsad ну они же от чего-то отталкивались, чтобы в приоритет определенные языки ставить

**Comment by Ibochkarev** [comment]
@bogdankorshunov не вносите смуту!

Все уже в процессе и на днях будет запущена офф дока с русским переводом на офф домене.

Смотреть тут https://github.com/vuejs/docs/pull/2757

**Comment by farid-temuri** [comment]
@bogdankorshunov мне интересно, что вы хотите сказать. Вы как бы пишите что-то, но не говорите ничего конкретного. Ни на какие ресурсы не сослались, ничего. Вы изначально написали бред и скинули ссылку на непонятно что. Кому-то достаточно сказать: [вот ссылка, поверь мне](https://youtu.be/dQw4w9WgXcQ?si=KM96t8zUDhR2TSrU), но я посмотрел ссылку и понял, что там 0 смысла, нету первого абзаца вашего и вы до сих пор пишите бред какой-то. Я не конспиролог, но это очень выглядит как ленива пропаганда идеи

**Comment by srsad** [comment]
@bogdankorshunov советую снять шапочку из фольги и просто начать жить😉
